--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aericio/PCEBookShop
build-by-default: true
branches:
- master
projects:
  PCEBookShop:
    path: ""
    libs:
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^1.0.1
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: ParoxityTeam/Commando/Commando
        version: ^2.1.0
    lint:
      phpstan: false
...
