# PCEBookShop Configuration File

economy:
  # Possible Providers: economyapi, multieconomy, xp
  provider: economyapi
  # This is used for the MultiEconomy provider
  multieconomy-currency: ""

cost:
  common: 1000
  uncommon: 2500
  rare: 5000
  mythic: 10000